require 'spec_helper'
require 'jekyll'

# Feature: jekyll-site-modernization, Property 20: Meta tag completeness
# Validates: Requirements 10.1, 10.4
RSpec.describe "Meta Tag Completeness" do
  let(:config) do
    Jekyll.configuration({
      'source' => '.',
      'destination' => './_site',
      'quiet' => true
    })
  end

  before(:all) do
    # Build the site once for all tests
    config = Jekyll.configuration({
      'source' => '.',
      'destination' => './_site',
      'quiet' => true
    })
    @site = Jekyll::Site.new(config)
    @site.process
  end

  describe "head include file" do
    let(:head_include) { File.read('_includes/head.html') }
    let(:built_index) { File.read('_site/index.html') }

    it "exists and is readable" do
      expect(File.exist?('_includes/head.html')).to be true
      expect(head_include).not_to be_empty
    end

    it "includes required meta tags" do
      required_meta_tags = [
        'charset',
        'viewport'
      ]

      # Check that basic meta tags are in the built HTML (generated by {% seo %})
      required_meta_tags.each do |meta_tag|
        expect(built_index).to match(/meta.*#{meta_tag}/i),
          "Built page should include '#{meta_tag}' meta tag"
      end
      
      # Description and keywords are generated by jekyll-seo-tag
      expect(built_index).to match(/meta.*description/i),
        "Built page should include description meta tag (from jekyll-seo-tag)"
    end

    it "includes title tag" do
      expect(built_index).to include('<title>'),
        "Built page should include title tag (from jekyll-seo-tag)"
    end

    it "includes canonical link tag" do
      expect(built_index).to match(/link.*rel=["']canonical["']/i),
        "Built page should include canonical link tag (from jekyll-seo-tag)"
    end

    it "includes Open Graph meta tags" do
      og_tags = [
        'og:title',
        'og:description',
        'og:url',
        'og:site_name',
        'og:type'
      ]

      # These are generated by jekyll-seo-tag at build time
      og_tags.each do |og_tag|
        expect(built_index).to match(/property=["']#{Regexp.escape(og_tag)}["']/i),
          "Built page should include '#{og_tag}' Open Graph tag (from jekyll-seo-tag)"
      end
    end

    it "includes Twitter Card meta tags" do
      twitter_tags = [
        'twitter:card',
        'twitter:title'
      ]

      # These are generated by jekyll-seo-tag at build time
      # Note: Jekyll SEO tag may use either name= or property= for Twitter tags
      twitter_tags.each do |twitter_tag|
        expect(built_index).to match(/(name|property)=["']#{Regexp.escape(twitter_tag)}["']/i),
          "Built page should include '#{twitter_tag}' Twitter Card tag (from jekyll-seo-tag)"
      end
    end
  end

  # Feature: jekyll-site-modernization, Property 20: Meta tag completeness
  # For any page in the Jekyll site, the HTML head should contain required meta tags
  # and Open Graph tags
  describe "property-based meta tag validation" do
    let(:test_pages) do
      [
        { 
          url: '/', 
          title: 'Home',
          layout: 'default',
          has_excerpt: false
        },
        { 
          url: '/about.html', 
          title: 'About',
          layout: 'page',
          has_excerpt: false
        },
        { 
          url: '/blog/', 
          title: 'Blog',
          layout: 'blog',
          has_excerpt: false
        },
        { 
          url: '/blog/2024/01/01/test-post/', 
          title: 'Test Post',
          layout: 'post',
          has_excerpt: true,
          tags: ['ruby', 'jekyll'],
          image: '/assets/images/test.jpg'
        },
        { 
          url: '/contact.html', 
          title: 'Contact',
          layout: 'page',
          has_excerpt: false
        }
      ]
    end

    it "ensures all pages have required meta tags in head" do
      pages = test_pages
      property_of {
        # Generate random page from test pages
        pages.sample
      }.check(100) do |page_data|
        # Check built HTML pages for meta tags (generated by jekyll-seo-tag)
        built_page_path = "_site#{page_data[:url]}"
        built_page_path += 'index.html' if page_data[:url].end_with?('/')
        
        if File.exist?(built_page_path)
          built_html = File.read(built_page_path)
          
          # Required meta tags should be present in built HTML
          required_tags = ['charset', 'viewport']
          
          required_tags.each do |tag|
            expect(built_html).to match(/meta.*#{tag}/i),
              "Page '#{page_data[:url]}' should have '#{tag}' meta tag in head"
          end
          
          # Title should be present
          expect(built_html).to include('<title>'),
            "Page '#{page_data[:url]}' should have title tag"
        end
      end
    end

    it "ensures all pages have Open Graph tags" do
      pages = test_pages
      property_of {
        # Generate random page from test pages
        pages.sample
      }.check(100) do |page_data|
        # Check built HTML pages for OG tags (generated by jekyll-seo-tag)
        built_page_path = "_site#{page_data[:url]}"
        built_page_path += 'index.html' if page_data[:url].end_with?('/')
        
        if File.exist?(built_page_path)
          built_html = File.read(built_page_path)
          
          # Required Open Graph tags
          required_og_tags = ['og:title', 'og:description', 'og:url', 'og:type']
          
          required_og_tags.each do |og_tag|
            expect(built_html).to match(/property=["']#{Regexp.escape(og_tag)}["']/i),
              "Page '#{page_data[:url]}' should have '#{og_tag}' Open Graph tag"
          end
        end
      end
    end

    it "validates meta tag structure and format" do
      pages = test_pages
      property_of {
        # Generate random page from test pages
        pages.sample
      }.check(100) do |page_data|
        # Check built HTML pages for meta tag structure
        built_page_path = "_site#{page_data[:url]}"
        built_page_path += 'index.html' if page_data[:url].end_with?('/')
        
        if File.exist?(built_page_path)
          built_html = File.read(built_page_path)
          
          # Meta tags should have proper structure
          # Check for meta tags with name or property attributes
          meta_tags = built_html.scan(/<meta\s+[^>]*>/)
          
          expect(meta_tags.length).to be > 0,
            "Page '#{page_data[:url]}' should have meta tags"
          
          # Each meta tag should have either name, property, http-equiv, or charset attribute
          meta_tags.each do |meta_tag|
            has_valid_attribute = meta_tag.match(/name=["'][^"']+["']/) || 
                                   meta_tag.match(/property=["'][^"']+["']/) ||
                                   meta_tag.match(/http-equiv=["'][^"']+["']/) ||
                                   meta_tag.match(/charset=/)
            
            expect(has_valid_attribute).to be_truthy,
              "Meta tag should have name, property, http-equiv, or charset attribute: #{meta_tag}"
          end
        end
      end
    end

    it "validates conditional meta tag logic for different page types" do
      pages = test_pages
      property_of {
        # Generate random page from test pages
        pages.sample
      }.check(100) do |page_data|
        # Check that jekyll-seo-tag is included in head.html
        head_include = File.read('_includes/head.html')
        
        # jekyll-seo-tag handles conditional logic for different page types
        expect(head_include).to match(/\{%\s*seo\s*%\}/),
          "Head should include jekyll-seo-tag which handles conditional meta tags"
      end
    end

    it "validates that meta descriptions use appropriate content" do
      pages = test_pages
      property_of {
        # Generate random page from test pages
        pages.sample
      }.check(100) do |page_data|
        # Check built HTML for description meta tag
        built_page_path = "_site#{page_data[:url]}"
        built_page_path += 'index.html' if page_data[:url].end_with?('/')
        
        if File.exist?(built_page_path)
          built_html = File.read(built_page_path)
          
          # Description meta tag should exist (generated by jekyll-seo-tag)
          expect(built_html).to match(/meta.*description/i),
            "Page '#{page_data[:url]}' should have description meta tag"
        end
      end
    end

    it "validates that keywords use appropriate content" do
      pages = test_pages
      property_of {
        # Generate random page from test pages
        pages.sample
      }.check(100) do |page_data|
        # Check that jekyll-seo-tag is included (it handles keywords)
        head_include = File.read('_includes/head.html')
        
        expect(head_include).to match(/\{%\s*seo\s*%\}/),
          "Head should include jekyll-seo-tag which handles keywords"
      end
    end

    it "ensures canonical URLs are properly set" do
      pages = test_pages
      property_of {
        # Generate random page from test pages
        pages.sample
      }.check(100) do |page_data|
        # Check built HTML for canonical link
        built_page_path = "_site#{page_data[:url]}"
        built_page_path += 'index.html' if page_data[:url].end_with?('/')
        
        if File.exist?(built_page_path)
          built_html = File.read(built_page_path)
          
          # Canonical link should exist (generated by jekyll-seo-tag)
          expect(built_html).to match(/link.*rel=["']canonical["']/i),
            "Page '#{page_data[:url]}' should have canonical link"
        end
      end
    end
  end

  describe "SEO plugin integration" do
    let(:head_include) { File.read('_includes/head.html') }

    it "includes jekyll-seo-tag plugin" do
      expect(head_include).to match(/\{%\s*seo\s*%\}/),
        "Head should include jekyll-seo-tag"
    end

    it "includes jekyll-feed plugin" do
      expect(head_include).to match(/\{%\s*feed_meta\s*%\}/),
        "Head should include jekyll-feed meta tag"
    end
  end

  describe "verification codes" do
    let(:head_include) { File.read('_includes/head.html') }

    it "includes conditional Google verification" do
      expect(head_include).to match(/\{%\s*if\s+site\.google_verify/),
        "Head should include conditional Google verification"
      expect(head_include).to match(/google-site-verification/),
        "Head should include Google verification meta tag"
    end

    it "includes conditional Bing verification" do
      expect(head_include).to match(/\{%\s*if\s+site\.bing_verify/),
        "Head should include conditional Bing verification"
      expect(head_include).to match(/msvalidate\.01/),
        "Head should include Bing verification meta tag"
    end
  end

  describe "asset links" do
    let(:head_include) { File.read('_includes/head.html') }

    it "includes Bootstrap 5 CSS" do
      expect(head_include).to match(/bootstrap.*\.css/i),
        "Head should include Bootstrap CSS"
    end

    it "includes custom CSS" do
      expect(head_include).to match(/assets\/css\/main\.css|style\.css/),
        "Head should include custom CSS file"
    end

    it "includes favicon" do
      expect(head_include).to match(/link.*icon/i),
        "Head should include favicon link"
    end

    it "includes font links" do
      expect(head_include).to match(/fonts\.googleapis\.com|fonts\.gstatic\.com/),
        "Head should include Google Fonts"
    end
  end

  describe "responsive and mobile meta tags" do
    let(:head_include) { File.read('_includes/head.html') }

    it "includes viewport meta tag for responsive design" do
      expect(head_include).to match(/meta.*viewport/i),
        "Head should include viewport meta tag"
      expect(head_include).to match(/width=device-width/i),
        "Viewport should set width to device-width"
    end

    it "includes proper charset declaration" do
      expect(head_include).to match(/meta.*charset.*utf-8/i),
        "Head should declare UTF-8 charset"
    end
  end
end
