require_relative 'spec_helper'

RSpec.describe "SEO and Feeds Configuration" do
  # Site should be built before running these tests
  # Run: bundle exec jekyll build

  describe "Jekyll SEO Tag Plugin" do
    it "generates meta tags in built pages" do
      index_html = File.read('_site/index.html')
      
      # Check for SEO meta tags generated by jekyll-seo-tag
      expect(index_html).to include('meta name="generator"')
      expect(index_html).to include('meta property="og:title"')
      expect(index_html).to include('meta property="og:locale"')
      expect(index_html).to include('meta name="description"')
      expect(index_html).to include('link rel="canonical"')
    end

    it "includes Twitter Card meta tags" do
      index_html = File.read('_site/index.html')
      
      expect(index_html).to include('meta name="twitter:card"')
      expect(index_html).to include('meta property="twitter:title"')
    end

    it "includes author information" do
      index_html = File.read('_site/index.html')
      
      expect(index_html).to include('meta name="author"')
    end
  end

  describe "Jekyll Sitemap Plugin" do
    it "generates sitemap.xml" do
      expect(File.exist?('_site/sitemap.xml')).to be true
    end

    it "includes all pages in sitemap" do
      sitemap = File.read('_site/sitemap.xml')
      
      expect(sitemap).to include('<urlset')
      expect(sitemap).to include('https://jdgoodall1.github.io/')
      expect(sitemap).to include('/about/')
      expect(sitemap).to include('/blog/')
      expect(sitemap).to include('/contact/')
    end

    it "includes blog posts in sitemap" do
      sitemap = File.read('_site/sitemap.xml')
      
      expect(sitemap).to include('/blog/2024/')
    end
  end

  describe "Jekyll Feed Plugin" do
    it "generates feed.xml" do
      expect(File.exist?('_site/feed.xml')).to be true
    end

    it "includes feed meta tag in pages" do
      index_html = File.read('_site/index.html')
      
      expect(index_html).to include('application/atom+xml')
      expect(index_html).to include('feed.xml')
    end

    it "includes blog posts in feed" do
      feed = File.read('_site/feed.xml')
      
      expect(feed).to include('<feed xmlns="http://www.w3.org/2005/Atom"')
      expect(feed).to include('<entry')
    end

    it "includes canonical URLs in feed entries" do
      feed = File.read('_site/feed.xml')
      
      expect(feed).to include('link href=')
      expect(feed).to include('rel="alternate"')
    end
  end

  describe "Robots.txt" do
    it "generates robots.txt" do
      expect(File.exist?('_site/robots.txt')).to be true
    end

    it "includes sitemap reference" do
      robots = File.read('_site/robots.txt')
      
      expect(robots).to include('Sitemap:')
      expect(robots).to include('sitemap.xml')
    end

    it "allows all user agents" do
      robots = File.read('_site/robots.txt')
      
      expect(robots).to include('User-agent: *')
      expect(robots).to include('Allow: /')
    end
  end

  describe "Verification Codes" do
    it "preserves Google verification code" do
      index_html = File.read('_site/index.html')
      
      expect(index_html).to include('google-site-verification')
      expect(index_html).to include('L2VsLI1uLyBPXQKO65ErOx1V5NYRQstKixSdR4HQW60')
    end

    it "preserves Bing verification code" do
      index_html = File.read('_site/index.html')
      
      expect(index_html).to include('msvalidate.01')
      expect(index_html).to include('86AD1A2F130F4DC2271E097B4D65EBBF')
    end
  end

  describe "Open Graph Tags" do
    it "includes Open Graph tags on all pages" do
      pages = ['_site/index.html', '_site/about/index.html', '_site/blog/index.html']
      
      pages.each do |page|
        next unless File.exist?(page)
        html = File.read(page)
        
        expect(html).to include('meta property="og:title"')
        expect(html).to include('meta property="og:description"')
        expect(html).to include('meta property="og:url"')
        expect(html).to include('meta property="og:site_name"')
      end
    end

    it "sets correct og:type for posts" do
      post_html = File.read('_site/blog/2024/12/01/sample-blog-post/index.html')
      
      expect(post_html).to include('meta property="og:type" content="article"')
    end
  end
end
